### ISSUE TITLE
Upgrade causes an issue with taskbar pin

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#115] opened 2016-07-20 19:10 UTC
Steps to Reproduce:

1. Install version 1.0.1
2. Pin the app to the taskbar
3. Use the shortcut to open nvQuickSite (it works)
4. Upgrade to version 1.1.0
5. Use the shortcut to open nvQuickSite

Expected Behavior:
nvQuickSite opens and you can create a site.

Actual Behavior:
Incorrect parameter error occurs. 

Workaround:
Remove the pin and re-pin the app to the taskbar again.

**Comment by nvisionative** [comment] 2016-07-20 21:23
Thank you for reporting this @hismightiness - will take a look into this.  Do you know if this happened also upgrading from 1.0.0 to 1.0.1?

**Comment by hismightiness** [comment] 2016-07-21 17:45
@nvisionative I don't remember if it happened on that upgrade too.  Sorry.

**Comment by nvisionative** [comment] 2016-07-21 17:54
No worries @hismightiness - our guess is it did.  We'll do some research.  Our thoughts are it is probably an issue with the MS installer project.

**Comment by nvisionative** [comment] 2016-07-23 02:23
@hismightiness we have an answer on this.  It appears this is expected behavior due to the Product Code and Package Code.  [Here is a pretty good explanation](https://blogs.msdn.microsoft.com/pusu/2009/06/10/what-are-upgrade-product-and-package-codes-used-for/) of the various codes and what it translates to as it relates to the installer.  We are going to go ahead and close this issue based on our findings.

**Closed by nvisionative** 2016-07-23 02:23 UTC
Labels: bug
