### ISSUE TITLE
Strange error "Some or all Identity references could not be translated"

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickSite#163] opened 2018-03-24 10:11 UTC
I usually get this error when using nvQuickSite (both v1.1 and 1.2). I don't know the cause - usually the installation will still succeeed, so I can't figure out what causes it.

![image](https://user-images.githubusercontent.com/5321186/37862832-13e02f60-2f54-11e8-839c-059665a42c7a.png)

**Comment by nvisionative** [comment] 2018-03-27 23:11
@iJungleboy I really thought we had finally resolved all this.  ;-(  

There are multiple calls to the **SetFolderPermission()** method in the **CreateDirectories()** method [HERE](https://github.com/nvisionative/nvQuickSite/blob/master/Start.cs#L578-L650).  The error is thrown in the **SetFolderPermissions()** method [HERE](https://github.com/nvisionative/nvQuickSite/blob/master/Start.cs#L666-L693).  Take a look and see if anything jumps out to you as odd.  

There are only three accounts used.  These are the variable names for those accounts and these variables do get conditionally manipulated based on environment variations.

- appPoolName
- dbServiceAccount
- authenticatedUsers

Reference [THIS](https://github.com/nvisionative/nvQuickSite/blob/master/Start.cs#L588-L590) for where the variables are defined.

The thing I am wondering now is does it have to do with the "Authenticated Users" identity/group?  See [THIS LINE](https://github.com/nvisionative/nvQuickSite/blob/master/Start.cs#L590).

**Comment by iJungleboy** [comment] 2018-03-28 03:31
I could only guess. In such a situation, I would create more try/catches to more precisely pinpoint the exact error. But in the long run, you'll probably want to add extensive logging or something. 

We added something like that in 2sxc 9.6 (https://2sxc.org/en/blog/post/releasing-2sxc-9-6-with-extensive-logging) and that helped a lot, because now we can usually just show the log of an task that is run. An since your tool doesn't have to optimize for performance anyhow, this wouldn't hurt it.

**Comment by nvisionative** [comment] 2018-03-28 14:37
Thanks @iJungleboy - our problem is that we can not reproduce the issue.  We don't mind implementing more try/catch blocks at all.  Would you be interested in helping us test?  We don't really want to publish a new version of nvQuickSite until we are able to isolate the problem and resolve it.  Thanks!

**Comment by iJungleboy** [comment] 2018-03-28 15:55
sure I'll help test. Just don't want to build it all - there's always something that needs a lot of work the first time you build something. you could just post the zip here, I'll pick it up....

**Comment by nvisionative** [comment] 2018-03-29 22:01
Sure thing @iJungleboy - I'll let you know as soon as we have a test build completed for you.  Thanks for your willingness to test!  That is the piece we have been missing with these obscure issues - being able to reproduce it.  :)

**Comment by abukres** [comment] 2018-04-04 06:07
@iJungleboy There's no work to build it. Click on the Open in the Visual Studio in Github and build. It should build without doing any work. In my case, the metroframework references were broken. I am not sure if Nuget had issues at the time or what. I had the app installed already so I added the references to those assemblies from the installation folder and the app built successfully. Run the app in debug mode with CLR exceptions enabled and VS should break at the line which caused the exception then report here.
I too could not reproduce your issue.

**Comment by dzsquared** [comment] 2018-04-04 16:45
I am also getting the error "Some or all Identity references could not be translated", which is immediately followed by this alert.
![error_alert](https://user-images.githubusercontent.com/12227241/38321413-3dd0920e-37fd-11e8-84be-430e3c992b78.PNG)
It is extremely strange especially since I am not setting up the DB on localhost.

**Comment by nvisionative** [comment] 2018-04-04 18:59
@dzsquared MSSQL Server must be installed on the same computer for nvQuickSite.  See [Minimum System Requirements](url).

@iJungleboy is your SQL Server on the same machine or remote?

**Comment by dzsquared** [comment] 2018-04-05 01:28
@nvisionative my fault for skipping over those. I tried to get running quickly from the quick start instructions on the homepage (http://www.nvquicksite.com/) thanks!

**Comment by iJungleboy** [comment] 2018-04-05 07:25
@nvisionative my setup has SQL on my PC, but as an instance, so it's (local)\SQLExpress - maybe that could be a cause?

**Comment by nvisionative** [comment] 2018-04-05 15:55
No worries @dzsquared.  :)

@iJungleboy SQL Server Express is supported.  We'll proceed with getting a new build to you as soon as possible.  We have a heavy project load right now, so it may be a bit.  Thanks for your patience.  We would like to get to the bottom of this error for sure!

**Comment by abukres** [comment] 2018-04-06 19:37
I got this error today. The rest of the installation goes fine. I ran it from within Visual Studio.
Then I tried twice again in debug mode and it didn't show up again. Because of this, I wasn't able to try to fix it.

**Comment by nvisionative** [comment] 2018-04-06 22:03
@abukres so it seems we are back to some sort of **_randomness_** that we need to trace down.  Perhaps adding some additional logging will help.  We have yet to have a chance to do this, but we try to get to it as soon as possible.

**Comment by abukres** [comment] 2018-04-06 22:07
@nvisionative Since this error doesn't seem to be affecting the DNN installation, maybe you want to handle it differently in the code.

**Comment by nvisionative** [comment] 2018-04-06 22:09
@abukres if you have specific ideas, we are certainly open to hearing them or receiving pull requests.

**Comment by SCullman** [comment] 2018-06-09 17:50
My PR fixes the handling of "Authenticated Users" which are localized within the international Windows distributions. It uses a SID to retrieve the translated name of the group.

**Comment by nvisionative** [comment] 2018-06-29 22:18
Resolved by PR #167

**Closed by nvisionative** 2018-06-29 22:18 UTC
Labels: bug, help wanted
