### ISSUE TITLE
Error: cannot access hosts

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickSite#171] opened 2018-07-30 06:41 UTC
In the last step of nvQuickSIte, after filling in the SQL user credentials, click Next: error, cannot access hosts.
I have restarted my PC, nvQUickSite is the 1st thing to do.
I can edit the hosts file manually (notepad/admin mode).

![image](https://user-images.githubusercontent.com/5859855/43381211-3ae682b4-93d4-11e8-959b-0a8d835860a9.png)

Note: I am working on a Dutch version of Windows.

**Comment by nvisionative** [comment] 2018-07-30 12:42
@EPTamminga thank you for reporting this issue.  It appears to be a permissions issue, as this is the first we have head of this happening.  Here are the typical permissions on the HOSTS file.

![screencapture_ 2018-07-30 08 39 am _1750](https://user-images.githubusercontent.com/4568451/43397858-37510f84-93d4-11e8-826a-efc355f1d42f.png)

Also, be sure no other program has that file open/locked.  nvQuickSite does in fact edit that file.

**Comment by EPTamminga** [comment] 2018-07-30 12:55
These permissions are (already) the same as shown
![image](https://user-images.githubusercontent.com/5859855/43398488-80249936-9408-11e8-9254-73f5322e1edb.png)

Difference: Dutch version of WIndows?

**Comment by nvisionative** [comment] 2018-07-30 12:57
@EPTamminga thank for confirming.  Perhaps there is something English specific in the code that needs some attention for international.  We'll review and circle back to you on this.

**Comment by EPTamminga** [comment] 2018-07-31 08:02
I stopped IIS, the problem remains
Executed the Process Explorer: I cannot find locks on the hosts file
Tried on another PC (NL version): the same problem
I will try to find an EN version PC and try it again

**Comment by nvisionative** [comment] 2018-08-02 12:10
@sholman are you too on a non-English version of Windows?

**Comment by EPTamminga** [comment] 2018-08-02 12:35
@nvisionative I tried an English version here as well. Problem remains.

**Comment by nvisionative** [comment] 2018-08-02 16:40
@EPTamminga you installed nvQuickSite on an English version of Windows 10 and you are still seeing this error?  If so, I am completely baffled.  There are hundreds of users of nvQuickSite, so you would think we would have heard about this by now if that were the case?

**Comment by sholman** [comment] 2018-08-02 22:29
@nvisionative No, an English version

**Comment by sholman** [comment] 2018-08-02 22:32
@EPTamminga Do you have current edits in your hosts file? I do. I would be surprised if that were the issue, but something to note.

**Comment by sholman** [comment] 2018-08-02 22:33
@nvisionative I also get this on my work PC (previous attempt was home PC) Both running Windows 10 Pro, one on a domain, one not.

**Comment by nvisionative** [comment] 2018-08-02 22:57
Could this potentially be related to some Windows Update?  We have not been able to reproduce the issue.

**Comment by sholman** [comment] 2018-08-02 23:02
@nvisionative Potentially. Both PC's are fairly up to date. I can manually update the hosts file (provided I run Notepad as Administrator)

**Comment by nvisionative** [comment] 2018-08-02 23:07
Here is the snippet of code that updates the HOSTS file:

```
        private bool UpdateHostsFile()
        {
            try
            {
                string hostsFile = Environment.GetFolderPath(Environment.SpecialFolder.System) + @"\drivers\etc\hosts";

                var newEntry = "\t127.0.0.1 \t" + txtSiteNamePrefix.Text + txtSiteNameSuffix.Text;
                if (!File.ReadAllLines(hostsFile).Contains(newEntry))
                {
                    if (File.ReadAllText(hostsFile).EndsWith(Environment.NewLine))
                    {
                        using (StreamWriter w = File.AppendText(hostsFile))
                        {
                            w.WriteLine(newEntry);
                        }
                    }
                    else
                    {
                        using (StreamWriter w = File.AppendText(hostsFile))
                        {
                            w.WriteLine(Environment.NewLine + newEntry);
                        }
                    }
                }
                return true;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error: " + ex.Message, "Update HOSTS File", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return false;
            }
        }
```

I see nothing here that could explain this behavior.

**Comment by sholman** [comment] 2018-08-02 23:13
It's clearly a permissions issue, but the app is running as Administrator, so it should work. Perhaps instead of putting a blocking error up, show the error and ask the user to add the line manually to their hosts file, but let it continue. I know this isn't ideal, but this blocking error makes the whole product unusable to me, and I can quite easily change my hosts file. Or, put in a checked be default checkbox for the hosts file change so people with this issue can uncheck it.

**Comment by sholman** [comment] 2018-08-02 23:30
I have tried to fork this repo and build it but am getting 60+ errors, mostly due to missing references for MetroFramework, but they Nuget shows that they have been installed. Is a specific version of this framework required?

**Comment by EPTamminga** [comment] 2018-08-03 07:02
I have edits in my hostfile.

I have cloned the repo begin of this week, solved the references, could build. I tried different things in the routine, 
* added "."after "hosts", to prevent folder mismatch (my windows always shows extensions and hidden files) --> no success
* Replaced the StreamWriter with File.AppendAllText(). --> No success,
* I made the program read & display the contents of hosts --> no problem
* I tried Windows process explore to find a lock --> none
* I tried to notepad/edit/admin the file while nvQuickSite was running (till the last screen) --> no problem
* Reviewed all possible problems (MSDN docs) related to the eeror --> no clue for me

The intermediate solution from @sholman (just mention the error and let me edit the hosts file manually)  would help me to be able to use nvQuickSite.

**Comment by EPTamminga** [comment] 2018-08-03 07:28
If I am not loggined into in my primary domain (work), but logged on to another network, I get an additonal error/warning (no trust relationship):

![image](https://user-images.githubusercontent.com/5859855/43630044-63803d5e-96ff-11e8-892f-01598ec43af6.png)

**Comment by EPTamminga** [comment] 2018-08-03 07:31
@sholman: Which anti-virus software are you using?
We use Kaspersky, which does checks program runtime behaviour. I cannot switch it off (controlled centrally).

**Comment by sholman** [comment] 2018-08-06 01:15
@EPTamminga We use Trend Micro. I will disable it (the joys of being the Administrator!) and test

**Comment by EPTamminga** [comment] 2018-08-06 07:26
@nvisionative @sholman OK, I got the option to pause anti-virus for limited time. 
Error on the hosts file permission gone, I can install using nvQuickSite.

But... I still get warnings about folder permissions (a number of times in the last step). Dutch error message screen capture (**Some or all identity references could not be translated**):

![image](https://user-images.githubusercontent.com/5859855/43702193-49eef3ec-9959-11e8-85a9-28e03fc6e6fd.png)

**Comment by nvisionative** [comment] 2018-08-06 12:57
@EPTamminga and @sholman - We are happy to hear you both got this working.  The recommendation is to configure anti-virus settings so this is no longer an issue.  Making changes to nvQuickSite to accommodate issues like this could very well be a slippery slope.  It is always best to address issue at the root.  We will add some lingo to the documentation to help others that may run into this issue in the future.

@sholman regarding the project compilation issues, please create a separate issue if you'd like to discuss.  In short though, this is a problem with not having NuGet packages in order.  You can try performing a "Clean" and a "Rebuild".

@EPTamminga regarding the **Set Folder Permissions** errors you are seeing, this has been a known issue for a long time (which we thought was fixed on various occasions), but the short of it is you can ignore them and most likely everything will work just fine.  If you need more information, please browse the issues.

**Comment by EPTamminga** [comment] 2018-08-08 17:08
I added a rule into the Kaspersky anti-virus software to ignore the application activity. 
Problem solved.

**Comment by nvisionative** [comment] 2018-08-08 18:52
@EPTamminga thanks.  We will leave this issue open so that information can be added to the documentation to help others that may run into this issue.

**Comment by sholman** [comment] 2018-08-10 00:36
I also added an exception for the hosts file in Trend and it works now.

**Comment by abukres** [comment] 2018-11-15 03:20
@nvisionative  Maybe you can trap this error and notify the user to either pause their antivirus while the app is running or tell them to add an exception to their antivirus for the hosts file.

**Comment by nvisionative** [comment] 2018-11-16 23:29
@abukres that's definitely a possibility.  I suggest a new issue be created specifically to address this idea and it can certainly reference this issue for background information.  Thanks!

**Closed by nvisionative** 2018-11-16 23:29 UTC
Labels: enhancement

**Comment by david-poindexter** [comment] 2021-09-18 03:02
@EPTamminga et al...
I recently made the switch to Kaspersky.  Here are my findings.  I know this is an old issue, but I thought my findings may help others.  Here is what I had to do in order to effectively use nvQuickSite with Kaspersky still running.  I don't like the idea of disabling it just to run an app.  😉 

First, go to Settings:
![image](https://user-images.githubusercontent.com/4568451/133870167-fb108933-6ecd-4b77-8f09-fef2fd4bc4c6.png)

Select `Threats and Exclusions`:
![image](https://user-images.githubusercontent.com/4568451/133870186-592347da-1589-4051-b800-8ea2a7b9052c.png)

Select `Specify trusted applications`:
![image](https://user-images.githubusercontent.com/4568451/133870204-2c43441d-9833-44eb-9bbc-f66e8d85889e.png)

Select `Add`:
![image](https://user-images.githubusercontent.com/4568451/133870256-62ab69a4-bdac-48f2-9790-7fb0a4315cac.png)

Select `nvQuickSite.exe`:
![image](https://user-images.githubusercontent.com/4568451/133870245-67a2b45f-6eda-48a9-946d-a206c0b8320a.png)

Select the following and click `OK`:
![image](https://user-images.githubusercontent.com/4568451/133870272-6ca80ebb-0131-4515-8c69-fe7436989486.png)

Click `OK` on `Trusted applications` window.

Click `Save` on `Settings > Threats and Exclusions` window.

I hope this helps - it worked like a charm for me!

**Comment by EPTamminga** [comment] 2021-09-18 06:29
That is What we did to get it working.

**Comment by hismightiness** [comment] 2021-09-20 19:35
In my case, I also had to allow the `HOSTS` file to be edited.
